// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webspice/webspicepb/webspice.proto

package webspicepb // import "webspice/webspicepb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User_Status int32

const (
	User_DEACTIVE User_Status = 0
	User_ACTIVE   User_Status = 1
)

var User_Status_name = map[int32]string{
	0: "DEACTIVE",
	1: "ACTIVE",
}
var User_Status_value = map[string]int32{
	"DEACTIVE": 0,
	"ACTIVE":   1,
}

func (x User_Status) String() string {
	return proto.EnumName(User_Status_name, int32(x))
}
func (User_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{8, 0}
}

type WebspiceRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebspiceRequest) Reset()         { *m = WebspiceRequest{} }
func (m *WebspiceRequest) String() string { return proto.CompactTextString(m) }
func (*WebspiceRequest) ProtoMessage()    {}
func (*WebspiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{0}
}
func (m *WebspiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebspiceRequest.Unmarshal(m, b)
}
func (m *WebspiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebspiceRequest.Marshal(b, m, deterministic)
}
func (dst *WebspiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebspiceRequest.Merge(dst, src)
}
func (m *WebspiceRequest) XXX_Size() int {
	return xxx_messageInfo_WebspiceRequest.Size(m)
}
func (m *WebspiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WebspiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WebspiceRequest proto.InternalMessageInfo

func (m *WebspiceRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *WebspiceRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type WebspiceResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebspiceResponse) Reset()         { *m = WebspiceResponse{} }
func (m *WebspiceResponse) String() string { return proto.CompactTextString(m) }
func (*WebspiceResponse) ProtoMessage()    {}
func (*WebspiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{1}
}
func (m *WebspiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebspiceResponse.Unmarshal(m, b)
}
func (m *WebspiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebspiceResponse.Marshal(b, m, deterministic)
}
func (dst *WebspiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebspiceResponse.Merge(dst, src)
}
func (m *WebspiceResponse) XXX_Size() int {
	return xxx_messageInfo_WebspiceResponse.Size(m)
}
func (m *WebspiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WebspiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WebspiceResponse proto.InternalMessageInfo

func (m *WebspiceResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type WebspiceManyRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebspiceManyRequest) Reset()         { *m = WebspiceManyRequest{} }
func (m *WebspiceManyRequest) String() string { return proto.CompactTextString(m) }
func (*WebspiceManyRequest) ProtoMessage()    {}
func (*WebspiceManyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{2}
}
func (m *WebspiceManyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebspiceManyRequest.Unmarshal(m, b)
}
func (m *WebspiceManyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebspiceManyRequest.Marshal(b, m, deterministic)
}
func (dst *WebspiceManyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebspiceManyRequest.Merge(dst, src)
}
func (m *WebspiceManyRequest) XXX_Size() int {
	return xxx_messageInfo_WebspiceManyRequest.Size(m)
}
func (m *WebspiceManyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WebspiceManyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WebspiceManyRequest proto.InternalMessageInfo

func (m *WebspiceManyRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *WebspiceManyRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type WebspiceManyResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebspiceManyResponse) Reset()         { *m = WebspiceManyResponse{} }
func (m *WebspiceManyResponse) String() string { return proto.CompactTextString(m) }
func (*WebspiceManyResponse) ProtoMessage()    {}
func (*WebspiceManyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{3}
}
func (m *WebspiceManyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebspiceManyResponse.Unmarshal(m, b)
}
func (m *WebspiceManyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebspiceManyResponse.Marshal(b, m, deterministic)
}
func (dst *WebspiceManyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebspiceManyResponse.Merge(dst, src)
}
func (m *WebspiceManyResponse) XXX_Size() int {
	return xxx_messageInfo_WebspiceManyResponse.Size(m)
}
func (m *WebspiceManyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WebspiceManyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WebspiceManyResponse proto.InternalMessageInfo

func (m *WebspiceManyResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type WebspiceLongRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebspiceLongRequest) Reset()         { *m = WebspiceLongRequest{} }
func (m *WebspiceLongRequest) String() string { return proto.CompactTextString(m) }
func (*WebspiceLongRequest) ProtoMessage()    {}
func (*WebspiceLongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{4}
}
func (m *WebspiceLongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebspiceLongRequest.Unmarshal(m, b)
}
func (m *WebspiceLongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebspiceLongRequest.Marshal(b, m, deterministic)
}
func (dst *WebspiceLongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebspiceLongRequest.Merge(dst, src)
}
func (m *WebspiceLongRequest) XXX_Size() int {
	return xxx_messageInfo_WebspiceLongRequest.Size(m)
}
func (m *WebspiceLongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WebspiceLongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WebspiceLongRequest proto.InternalMessageInfo

func (m *WebspiceLongRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *WebspiceLongRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type WebspiceLongResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebspiceLongResponse) Reset()         { *m = WebspiceLongResponse{} }
func (m *WebspiceLongResponse) String() string { return proto.CompactTextString(m) }
func (*WebspiceLongResponse) ProtoMessage()    {}
func (*WebspiceLongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{5}
}
func (m *WebspiceLongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebspiceLongResponse.Unmarshal(m, b)
}
func (m *WebspiceLongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebspiceLongResponse.Marshal(b, m, deterministic)
}
func (dst *WebspiceLongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebspiceLongResponse.Merge(dst, src)
}
func (m *WebspiceLongResponse) XXX_Size() int {
	return xxx_messageInfo_WebspiceLongResponse.Size(m)
}
func (m *WebspiceLongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WebspiceLongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WebspiceLongResponse proto.InternalMessageInfo

func (m *WebspiceLongResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type WebspiceEveryDomainRequest struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebspiceEveryDomainRequest) Reset()         { *m = WebspiceEveryDomainRequest{} }
func (m *WebspiceEveryDomainRequest) String() string { return proto.CompactTextString(m) }
func (*WebspiceEveryDomainRequest) ProtoMessage()    {}
func (*WebspiceEveryDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{6}
}
func (m *WebspiceEveryDomainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebspiceEveryDomainRequest.Unmarshal(m, b)
}
func (m *WebspiceEveryDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebspiceEveryDomainRequest.Marshal(b, m, deterministic)
}
func (dst *WebspiceEveryDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebspiceEveryDomainRequest.Merge(dst, src)
}
func (m *WebspiceEveryDomainRequest) XXX_Size() int {
	return xxx_messageInfo_WebspiceEveryDomainRequest.Size(m)
}
func (m *WebspiceEveryDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WebspiceEveryDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WebspiceEveryDomainRequest proto.InternalMessageInfo

func (m *WebspiceEveryDomainRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type WebspiceEveryDomainResponse struct {
	Result               []string `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebspiceEveryDomainResponse) Reset()         { *m = WebspiceEveryDomainResponse{} }
func (m *WebspiceEveryDomainResponse) String() string { return proto.CompactTextString(m) }
func (*WebspiceEveryDomainResponse) ProtoMessage()    {}
func (*WebspiceEveryDomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{7}
}
func (m *WebspiceEveryDomainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebspiceEveryDomainResponse.Unmarshal(m, b)
}
func (m *WebspiceEveryDomainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebspiceEveryDomainResponse.Marshal(b, m, deterministic)
}
func (dst *WebspiceEveryDomainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebspiceEveryDomainResponse.Merge(dst, src)
}
func (m *WebspiceEveryDomainResponse) XXX_Size() int {
	return xxx_messageInfo_WebspiceEveryDomainResponse.Size(m)
}
func (m *WebspiceEveryDomainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WebspiceEveryDomainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WebspiceEveryDomainResponse proto.InternalMessageInfo

func (m *WebspiceEveryDomainResponse) GetResult() []string {
	if m != nil {
		return m.Result
	}
	return nil
}

type User struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string      `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string      `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone                string      `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedAt            string      `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Permissions          []string    `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Status               User_Status `protobuf:"varint,7,opt,name=status,proto3,enum=webspice.User_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{8}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *User) GetStatus() User_Status {
	if m != nil {
		return m.Status
	}
	return User_DEACTIVE
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{9}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{10}
}
func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (dst *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(dst, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{11}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(dst, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{12}
}
func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(dst, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{13}
}
func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(dst, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{14}
}
func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(dst, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SearchUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUserRequest) Reset()         { *m = SearchUserRequest{} }
func (m *SearchUserRequest) String() string { return proto.CompactTextString(m) }
func (*SearchUserRequest) ProtoMessage()    {}
func (*SearchUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{15}
}
func (m *SearchUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUserRequest.Unmarshal(m, b)
}
func (m *SearchUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUserRequest.Marshal(b, m, deterministic)
}
func (dst *SearchUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUserRequest.Merge(dst, src)
}
func (m *SearchUserRequest) XXX_Size() int {
	return xxx_messageInfo_SearchUserRequest.Size(m)
}
func (m *SearchUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUserRequest proto.InternalMessageInfo

func (m *SearchUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SearchUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUserResponse) Reset()         { *m = SearchUserResponse{} }
func (m *SearchUserResponse) String() string { return proto.CompactTextString(m) }
func (*SearchUserResponse) ProtoMessage()    {}
func (*SearchUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{16}
}
func (m *SearchUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUserResponse.Unmarshal(m, b)
}
func (m *SearchUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUserResponse.Marshal(b, m, deterministic)
}
func (dst *SearchUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUserResponse.Merge(dst, src)
}
func (m *SearchUserResponse) XXX_Size() int {
	return xxx_messageInfo_SearchUserResponse.Size(m)
}
func (m *SearchUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUserResponse proto.InternalMessageInfo

func (m *SearchUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SearchUserManyRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUserManyRequest) Reset()         { *m = SearchUserManyRequest{} }
func (m *SearchUserManyRequest) String() string { return proto.CompactTextString(m) }
func (*SearchUserManyRequest) ProtoMessage()    {}
func (*SearchUserManyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{17}
}
func (m *SearchUserManyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUserManyRequest.Unmarshal(m, b)
}
func (m *SearchUserManyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUserManyRequest.Marshal(b, m, deterministic)
}
func (dst *SearchUserManyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUserManyRequest.Merge(dst, src)
}
func (m *SearchUserManyRequest) XXX_Size() int {
	return xxx_messageInfo_SearchUserManyRequest.Size(m)
}
func (m *SearchUserManyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUserManyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUserManyRequest proto.InternalMessageInfo

func (m *SearchUserManyRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SearchUserManyResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUserManyResponse) Reset()         { *m = SearchUserManyResponse{} }
func (m *SearchUserManyResponse) String() string { return proto.CompactTextString(m) }
func (*SearchUserManyResponse) ProtoMessage()    {}
func (*SearchUserManyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{18}
}
func (m *SearchUserManyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUserManyResponse.Unmarshal(m, b)
}
func (m *SearchUserManyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUserManyResponse.Marshal(b, m, deterministic)
}
func (dst *SearchUserManyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUserManyResponse.Merge(dst, src)
}
func (m *SearchUserManyResponse) XXX_Size() int {
	return xxx_messageInfo_SearchUserManyResponse.Size(m)
}
func (m *SearchUserManyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUserManyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUserManyResponse proto.InternalMessageInfo

func (m *SearchUserManyResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SearchEveryUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchEveryUserRequest) Reset()         { *m = SearchEveryUserRequest{} }
func (m *SearchEveryUserRequest) String() string { return proto.CompactTextString(m) }
func (*SearchEveryUserRequest) ProtoMessage()    {}
func (*SearchEveryUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{19}
}
func (m *SearchEveryUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchEveryUserRequest.Unmarshal(m, b)
}
func (m *SearchEveryUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchEveryUserRequest.Marshal(b, m, deterministic)
}
func (dst *SearchEveryUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchEveryUserRequest.Merge(dst, src)
}
func (m *SearchEveryUserRequest) XXX_Size() int {
	return xxx_messageInfo_SearchEveryUserRequest.Size(m)
}
func (m *SearchEveryUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchEveryUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchEveryUserRequest proto.InternalMessageInfo

func (m *SearchEveryUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SearchEveryUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchEveryUserResponse) Reset()         { *m = SearchEveryUserResponse{} }
func (m *SearchEveryUserResponse) String() string { return proto.CompactTextString(m) }
func (*SearchEveryUserResponse) ProtoMessage()    {}
func (*SearchEveryUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_webspice_8ca558bb50336e65, []int{20}
}
func (m *SearchEveryUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchEveryUserResponse.Unmarshal(m, b)
}
func (m *SearchEveryUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchEveryUserResponse.Marshal(b, m, deterministic)
}
func (dst *SearchEveryUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchEveryUserResponse.Merge(dst, src)
}
func (m *SearchEveryUserResponse) XXX_Size() int {
	return xxx_messageInfo_SearchEveryUserResponse.Size(m)
}
func (m *SearchEveryUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchEveryUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchEveryUserResponse proto.InternalMessageInfo

func (m *SearchEveryUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*WebspiceRequest)(nil), "webspice.WebspiceRequest")
	proto.RegisterType((*WebspiceResponse)(nil), "webspice.WebspiceResponse")
	proto.RegisterType((*WebspiceManyRequest)(nil), "webspice.WebspiceManyRequest")
	proto.RegisterType((*WebspiceManyResponse)(nil), "webspice.WebspiceManyResponse")
	proto.RegisterType((*WebspiceLongRequest)(nil), "webspice.WebspiceLongRequest")
	proto.RegisterType((*WebspiceLongResponse)(nil), "webspice.WebspiceLongResponse")
	proto.RegisterType((*WebspiceEveryDomainRequest)(nil), "webspice.WebspiceEveryDomainRequest")
	proto.RegisterType((*WebspiceEveryDomainResponse)(nil), "webspice.WebspiceEveryDomainResponse")
	proto.RegisterType((*User)(nil), "webspice.User")
	proto.RegisterType((*CreateUserRequest)(nil), "webspice.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "webspice.CreateUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "webspice.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "webspice.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "webspice.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "webspice.DeleteUserResponse")
	proto.RegisterType((*SearchUserRequest)(nil), "webspice.SearchUserRequest")
	proto.RegisterType((*SearchUserResponse)(nil), "webspice.SearchUserResponse")
	proto.RegisterType((*SearchUserManyRequest)(nil), "webspice.SearchUserManyRequest")
	proto.RegisterType((*SearchUserManyResponse)(nil), "webspice.SearchUserManyResponse")
	proto.RegisterType((*SearchEveryUserRequest)(nil), "webspice.SearchEveryUserRequest")
	proto.RegisterType((*SearchEveryUserResponse)(nil), "webspice.SearchEveryUserResponse")
	proto.RegisterEnum("webspice.User_Status", User_Status_name, User_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WebspiceClient is the client API for Webspice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebspiceClient interface {
	Webspice(ctx context.Context, in *WebspiceRequest, opts ...grpc.CallOption) (*WebspiceResponse, error)
	WebspiceMany(ctx context.Context, in *WebspiceManyRequest, opts ...grpc.CallOption) (Webspice_WebspiceManyClient, error)
	WebspiceLong(ctx context.Context, opts ...grpc.CallOption) (Webspice_WebspiceLongClient, error)
	WebspiceEveryDomain(ctx context.Context, opts ...grpc.CallOption) (Webspice_WebspiceEveryDomainClient, error)
	// users CROD
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	SearchUser(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error)
	// stream get all Users
	SearchUserMany(ctx context.Context, in *SearchUserManyRequest, opts ...grpc.CallOption) (Webspice_SearchUserManyClient, error)
	// EveryStream
	SearchEveryUser(ctx context.Context, opts ...grpc.CallOption) (Webspice_SearchEveryUserClient, error)
}

type webspiceClient struct {
	cc *grpc.ClientConn
}

func NewWebspiceClient(cc *grpc.ClientConn) WebspiceClient {
	return &webspiceClient{cc}
}

func (c *webspiceClient) Webspice(ctx context.Context, in *WebspiceRequest, opts ...grpc.CallOption) (*WebspiceResponse, error) {
	out := new(WebspiceResponse)
	err := c.cc.Invoke(ctx, "/webspice.Webspice/Webspice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webspiceClient) WebspiceMany(ctx context.Context, in *WebspiceManyRequest, opts ...grpc.CallOption) (Webspice_WebspiceManyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Webspice_serviceDesc.Streams[0], "/webspice.Webspice/WebspiceMany", opts...)
	if err != nil {
		return nil, err
	}
	x := &webspiceWebspiceManyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Webspice_WebspiceManyClient interface {
	Recv() (*WebspiceManyResponse, error)
	grpc.ClientStream
}

type webspiceWebspiceManyClient struct {
	grpc.ClientStream
}

func (x *webspiceWebspiceManyClient) Recv() (*WebspiceManyResponse, error) {
	m := new(WebspiceManyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *webspiceClient) WebspiceLong(ctx context.Context, opts ...grpc.CallOption) (Webspice_WebspiceLongClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Webspice_serviceDesc.Streams[1], "/webspice.Webspice/WebspiceLong", opts...)
	if err != nil {
		return nil, err
	}
	x := &webspiceWebspiceLongClient{stream}
	return x, nil
}

type Webspice_WebspiceLongClient interface {
	Send(*WebspiceLongRequest) error
	CloseAndRecv() (*WebspiceLongResponse, error)
	grpc.ClientStream
}

type webspiceWebspiceLongClient struct {
	grpc.ClientStream
}

func (x *webspiceWebspiceLongClient) Send(m *WebspiceLongRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *webspiceWebspiceLongClient) CloseAndRecv() (*WebspiceLongResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WebspiceLongResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *webspiceClient) WebspiceEveryDomain(ctx context.Context, opts ...grpc.CallOption) (Webspice_WebspiceEveryDomainClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Webspice_serviceDesc.Streams[2], "/webspice.Webspice/WebspiceEveryDomain", opts...)
	if err != nil {
		return nil, err
	}
	x := &webspiceWebspiceEveryDomainClient{stream}
	return x, nil
}

type Webspice_WebspiceEveryDomainClient interface {
	Send(*WebspiceEveryDomainRequest) error
	Recv() (*WebspiceEveryDomainResponse, error)
	grpc.ClientStream
}

type webspiceWebspiceEveryDomainClient struct {
	grpc.ClientStream
}

func (x *webspiceWebspiceEveryDomainClient) Send(m *WebspiceEveryDomainRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *webspiceWebspiceEveryDomainClient) Recv() (*WebspiceEveryDomainResponse, error) {
	m := new(WebspiceEveryDomainResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *webspiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/webspice.Webspice/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webspiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/webspice.Webspice/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webspiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/webspice.Webspice/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webspiceClient) SearchUser(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error) {
	out := new(SearchUserResponse)
	err := c.cc.Invoke(ctx, "/webspice.Webspice/SearchUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webspiceClient) SearchUserMany(ctx context.Context, in *SearchUserManyRequest, opts ...grpc.CallOption) (Webspice_SearchUserManyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Webspice_serviceDesc.Streams[3], "/webspice.Webspice/SearchUserMany", opts...)
	if err != nil {
		return nil, err
	}
	x := &webspiceSearchUserManyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Webspice_SearchUserManyClient interface {
	Recv() (*SearchUserManyResponse, error)
	grpc.ClientStream
}

type webspiceSearchUserManyClient struct {
	grpc.ClientStream
}

func (x *webspiceSearchUserManyClient) Recv() (*SearchUserManyResponse, error) {
	m := new(SearchUserManyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *webspiceClient) SearchEveryUser(ctx context.Context, opts ...grpc.CallOption) (Webspice_SearchEveryUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Webspice_serviceDesc.Streams[4], "/webspice.Webspice/SearchEveryUser", opts...)
	if err != nil {
		return nil, err
	}
	x := &webspiceSearchEveryUserClient{stream}
	return x, nil
}

type Webspice_SearchEveryUserClient interface {
	Send(*SearchEveryUserRequest) error
	Recv() (*SearchEveryUserResponse, error)
	grpc.ClientStream
}

type webspiceSearchEveryUserClient struct {
	grpc.ClientStream
}

func (x *webspiceSearchEveryUserClient) Send(m *SearchEveryUserRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *webspiceSearchEveryUserClient) Recv() (*SearchEveryUserResponse, error) {
	m := new(SearchEveryUserResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WebspiceServer is the server API for Webspice service.
type WebspiceServer interface {
	Webspice(context.Context, *WebspiceRequest) (*WebspiceResponse, error)
	WebspiceMany(*WebspiceManyRequest, Webspice_WebspiceManyServer) error
	WebspiceLong(Webspice_WebspiceLongServer) error
	WebspiceEveryDomain(Webspice_WebspiceEveryDomainServer) error
	// users CROD
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	SearchUser(context.Context, *SearchUserRequest) (*SearchUserResponse, error)
	// stream get all Users
	SearchUserMany(*SearchUserManyRequest, Webspice_SearchUserManyServer) error
	// EveryStream
	SearchEveryUser(Webspice_SearchEveryUserServer) error
}

func RegisterWebspiceServer(s *grpc.Server, srv WebspiceServer) {
	s.RegisterService(&_Webspice_serviceDesc, srv)
}

func _Webspice_Webspice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebspiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebspiceServer).Webspice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webspice.Webspice/Webspice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebspiceServer).Webspice(ctx, req.(*WebspiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webspice_WebspiceMany_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WebspiceManyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WebspiceServer).WebspiceMany(m, &webspiceWebspiceManyServer{stream})
}

type Webspice_WebspiceManyServer interface {
	Send(*WebspiceManyResponse) error
	grpc.ServerStream
}

type webspiceWebspiceManyServer struct {
	grpc.ServerStream
}

func (x *webspiceWebspiceManyServer) Send(m *WebspiceManyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Webspice_WebspiceLong_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WebspiceServer).WebspiceLong(&webspiceWebspiceLongServer{stream})
}

type Webspice_WebspiceLongServer interface {
	SendAndClose(*WebspiceLongResponse) error
	Recv() (*WebspiceLongRequest, error)
	grpc.ServerStream
}

type webspiceWebspiceLongServer struct {
	grpc.ServerStream
}

func (x *webspiceWebspiceLongServer) SendAndClose(m *WebspiceLongResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *webspiceWebspiceLongServer) Recv() (*WebspiceLongRequest, error) {
	m := new(WebspiceLongRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Webspice_WebspiceEveryDomain_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WebspiceServer).WebspiceEveryDomain(&webspiceWebspiceEveryDomainServer{stream})
}

type Webspice_WebspiceEveryDomainServer interface {
	Send(*WebspiceEveryDomainResponse) error
	Recv() (*WebspiceEveryDomainRequest, error)
	grpc.ServerStream
}

type webspiceWebspiceEveryDomainServer struct {
	grpc.ServerStream
}

func (x *webspiceWebspiceEveryDomainServer) Send(m *WebspiceEveryDomainResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *webspiceWebspiceEveryDomainServer) Recv() (*WebspiceEveryDomainRequest, error) {
	m := new(WebspiceEveryDomainRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Webspice_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebspiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webspice.Webspice/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebspiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webspice_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebspiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webspice.Webspice/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebspiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webspice_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebspiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webspice.Webspice/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebspiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webspice_SearchUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebspiceServer).SearchUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webspice.Webspice/SearchUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebspiceServer).SearchUser(ctx, req.(*SearchUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webspice_SearchUserMany_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchUserManyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WebspiceServer).SearchUserMany(m, &webspiceSearchUserManyServer{stream})
}

type Webspice_SearchUserManyServer interface {
	Send(*SearchUserManyResponse) error
	grpc.ServerStream
}

type webspiceSearchUserManyServer struct {
	grpc.ServerStream
}

func (x *webspiceSearchUserManyServer) Send(m *SearchUserManyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Webspice_SearchEveryUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WebspiceServer).SearchEveryUser(&webspiceSearchEveryUserServer{stream})
}

type Webspice_SearchEveryUserServer interface {
	Send(*SearchEveryUserResponse) error
	Recv() (*SearchEveryUserRequest, error)
	grpc.ServerStream
}

type webspiceSearchEveryUserServer struct {
	grpc.ServerStream
}

func (x *webspiceSearchEveryUserServer) Send(m *SearchEveryUserResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *webspiceSearchEveryUserServer) Recv() (*SearchEveryUserRequest, error) {
	m := new(SearchEveryUserRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Webspice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webspice.Webspice",
	HandlerType: (*WebspiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Webspice",
			Handler:    _Webspice_Webspice_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Webspice_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Webspice_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Webspice_DeleteUser_Handler,
		},
		{
			MethodName: "SearchUser",
			Handler:    _Webspice_SearchUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WebspiceMany",
			Handler:       _Webspice_WebspiceMany_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WebspiceLong",
			Handler:       _Webspice_WebspiceLong_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WebspiceEveryDomain",
			Handler:       _Webspice_WebspiceEveryDomain_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SearchUserMany",
			Handler:       _Webspice_SearchUserMany_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchEveryUser",
			Handler:       _Webspice_SearchEveryUser_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "webspice/webspicepb/webspice.proto",
}

func init() {
	proto.RegisterFile("webspice/webspicepb/webspice.proto", fileDescriptor_webspice_8ca558bb50336e65)
}

var fileDescriptor_webspice_8ca558bb50336e65 = []byte{
	// 625 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0xfd, 0xa5, 0x7f, 0xf2, 0x6b, 0xef, 0xa6, 0xae, 0xf3, 0xd6, 0x12, 0x52, 0x06, 0x25, 0x02,
	0xa9, 0x42, 0xa2, 0x4c, 0x05, 0x34, 0x24, 0xe0, 0xa1, 0x5b, 0x4b, 0x85, 0xc4, 0x1f, 0xa9, 0xa3,
	0x20, 0xed, 0x65, 0x4a, 0x5b, 0x6f, 0x8b, 0xd4, 0x26, 0x21, 0x4e, 0x41, 0xfb, 0x52, 0x7c, 0x42,
	0x1e, 0x50, 0x9c, 0xa4, 0xbe, 0x4d, 0x3c, 0xd6, 0x54, 0xbc, 0xd9, 0xf7, 0xde, 0x73, 0x4e, 0xed,
	0xfa, 0x1c, 0x05, 0x8c, 0x9f, 0x74, 0xcc, 0x5c, 0x6b, 0x42, 0x9f, 0xc5, 0x0b, 0x77, 0xbc, 0x5c,
	0xb6, 0x5d, 0xcf, 0xf1, 0x1d, 0x52, 0x8a, 0xf7, 0xc6, 0x31, 0xec, 0x7c, 0x8b, 0xd6, 0x43, 0xfa,
	0x7d, 0x41, 0x99, 0x4f, 0x0e, 0x00, 0x2e, 0x2c, 0x8f, 0xf9, 0xe7, 0xb6, 0x39, 0xa7, 0x9a, 0xd2,
	0x54, 0x5a, 0xe5, 0x61, 0x99, 0x57, 0x3e, 0x99, 0x73, 0x4a, 0xaa, 0x90, 0x37, 0x2f, 0xa9, 0x96,
	0x6b, 0x2a, 0xad, 0xe2, 0x30, 0x58, 0x1a, 0x4f, 0xa0, 0x2a, 0x38, 0x98, 0xeb, 0xd8, 0x8c, 0x92,
	0x3a, 0xa8, 0x1e, 0x65, 0x8b, 0x99, 0x1f, 0x11, 0x44, 0x3b, 0xe3, 0x1d, 0xec, 0xc5, 0xb3, 0x1f,
	0x4d, 0xfb, 0x7a, 0x63, 0xcd, 0x36, 0xec, 0xaf, 0xf2, 0xac, 0xaf, 0xfb, 0xc1, 0xb1, 0x2f, 0xff,
	0x85, 0x6e, 0xc8, 0x73, 0x8b, 0xee, 0x0b, 0xd0, 0xe3, 0xf9, 0xfe, 0x0f, 0xea, 0x5d, 0xf7, 0x9c,
	0xb9, 0x69, 0xd9, 0xb1, 0x7c, 0x1d, 0xd4, 0x29, 0x2f, 0xc4, 0xa8, 0x70, 0x67, 0xbc, 0x84, 0x86,
	0x14, 0x25, 0x11, 0xcb, 0x23, 0xb1, 0xdf, 0x0a, 0x14, 0x46, 0x8c, 0x7a, 0xa4, 0x02, 0x39, 0x6b,
	0x1a, 0x71, 0xe6, 0xac, 0x69, 0xe2, 0x98, 0xb9, 0xe4, 0x31, 0x1b, 0x50, 0x9e, 0x99, 0x71, 0x37,
	0xcf, 0xbb, 0xa5, 0xa0, 0xc0, 0x9b, 0xfb, 0x50, 0x74, 0xaf, 0x1c, 0x9b, 0x6a, 0x05, 0xde, 0x08,
	0x37, 0x01, 0xe3, 0xc4, 0xa3, 0xa6, 0x4f, 0xa7, 0xe7, 0xa6, 0xaf, 0x15, 0x43, 0xc6, 0xa8, 0xd2,
	0xf5, 0x49, 0x13, 0xb6, 0x5c, 0xea, 0xcd, 0x2d, 0xc6, 0x2c, 0xc7, 0x66, 0x9a, 0xca, 0x7f, 0x26,
	0x2e, 0x91, 0xa7, 0xa0, 0x32, 0xdf, 0xf4, 0x17, 0x4c, 0xfb, 0xbf, 0xa9, 0xb4, 0x2a, 0x9d, 0x5a,
	0x7b, 0xf9, 0x46, 0x83, 0x23, 0xb4, 0x4f, 0x79, 0x73, 0x18, 0x0d, 0x19, 0x06, 0xa8, 0x61, 0x85,
	0x6c, 0x43, 0xa9, 0xd7, 0xef, 0x9e, 0x7c, 0x79, 0xff, 0xb5, 0x5f, 0xfd, 0x8f, 0x00, 0xa8, 0xd1,
	0x5a, 0x31, 0x8e, 0x60, 0xf7, 0x84, 0xff, 0x82, 0x80, 0x20, 0xbe, 0x62, 0x03, 0x0a, 0x0b, 0x46,
	0x3d, 0x7e, 0x19, 0x5b, 0x9d, 0xca, 0xaa, 0xca, 0x90, 0xf7, 0x8c, 0x57, 0x40, 0x30, 0x30, 0xba,
	0xe5, 0x75, 0x90, 0x47, 0xb0, 0x3b, 0x72, 0xa7, 0x9b, 0x49, 0x62, 0x60, 0x36, 0xc9, 0x1e, 0x9d,
	0xd1, 0x8d, 0x24, 0x31, 0x30, 0x9b, 0xe4, 0x29, 0x35, 0xbd, 0xc9, 0xd5, 0x06, 0x92, 0x18, 0x98,
	0x41, 0xf2, 0x35, 0xd4, 0x04, 0x12, 0x27, 0xc5, 0x3a, 0xe0, 0x37, 0x50, 0x4f, 0x82, 0x33, 0x48,
	0x2f, 0xd1, 0xdc, 0x7a, 0x59, 0x8f, 0xfc, 0x16, 0xee, 0xa4, 0xd0, 0xeb, 0x8b, 0x77, 0x7e, 0xa9,
	0x50, 0x8a, 0xad, 0x4f, 0xba, 0x68, 0x7d, 0x57, 0x8c, 0x27, 0x02, 0x5b, 0xd7, 0x65, 0xad, 0x48,
	0xf3, 0x33, 0x6c, 0xe3, 0x9c, 0x24, 0x07, 0xe9, 0x59, 0x74, 0xbb, 0xfa, 0xfd, 0x9b, 0xda, 0x21,
	0xdd, 0xa1, 0x82, 0x09, 0x83, 0x00, 0x94, 0x11, 0xa2, 0x80, 0x95, 0x11, 0xe2, 0xdc, 0x6c, 0x29,
	0xe4, 0x42, 0x24, 0x33, 0xca, 0x3a, 0xf2, 0x28, 0x0d, 0x4c, 0x07, 0xa8, 0xfe, 0xf8, 0x96, 0xa9,
	0x58, 0xe5, 0x50, 0x21, 0x03, 0x00, 0x61, 0x72, 0xd2, 0x10, 0xc0, 0x54, 0x66, 0xe8, 0xf7, 0xe4,
	0xcd, 0xe8, 0x4a, 0x07, 0x00, 0xc2, 0xba, 0x98, 0x28, 0x95, 0x04, 0x98, 0x48, 0xe2, 0xf6, 0x01,
	0x80, 0x30, 0x24, 0x26, 0x4a, 0xf9, 0x1b, 0x13, 0x49, 0x3c, 0x3c, 0x00, 0x10, 0xef, 0x1d, 0x13,
	0xa5, 0x5c, 0x8b, 0x89, 0x24, 0xce, 0x1c, 0x41, 0x65, 0xd5, 0x38, 0xe4, 0x81, 0x6c, 0x1e, 0xbf,
	0x98, 0xe6, 0xcd, 0x03, 0xcb, 0x37, 0x73, 0x06, 0x3b, 0x09, 0x4f, 0x90, 0x14, 0x2c, 0x69, 0x36,
	0xfd, 0xe1, 0x5f, 0x26, 0xc4, 0xdf, 0x7a, 0x5c, 0x3b, 0xdb, 0x93, 0x7c, 0xf0, 0x8c, 0x55, 0xfe,
	0xa1, 0xf3, 0xfc, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x52, 0x41, 0x7c, 0x0e, 0x09, 0x00,
	0x00,
}
