// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog/blogpb/blog.proto

package blogpb // import "blog/blogpb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Blog_Gender int32

const (
	Blog_Male  Blog_Gender = 0
	Blog_Fmale Blog_Gender = 1
)

var Blog_Gender_name = map[int32]string{
	0: "Male",
	1: "Fmale",
}
var Blog_Gender_value = map[string]int32{
	"Male":  0,
	"Fmale": 1,
}

func (x Blog_Gender) String() string {
	return proto.EnumName(Blog_Gender_name, int32(x))
}
func (Blog_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_blog_4f48964a2499a65d, []int{0, 0}
}

type Blog struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32       `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string      `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string      `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Tags                 []string    `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Phone                string      `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender               Blog_Gender `protobuf:"varint,7,opt,name=gender,proto3,enum=blog.Blog_Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_4f48964a2499a65d, []int{0}
}
func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (dst *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(dst, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blog) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Blog) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Blog) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Blog) GetGender() Blog_Gender {
	if m != nil {
		return m.Gender
	}
	return Blog_Male
}

type CreateBlogRequest struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBlogRequest) Reset()         { *m = CreateBlogRequest{} }
func (m *CreateBlogRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBlogRequest) ProtoMessage()    {}
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_4f48964a2499a65d, []int{1}
}
func (m *CreateBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogRequest.Unmarshal(m, b)
}
func (m *CreateBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogRequest.Marshal(b, m, deterministic)
}
func (dst *CreateBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogRequest.Merge(dst, src)
}
func (m *CreateBlogRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBlogRequest.Size(m)
}
func (m *CreateBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogRequest proto.InternalMessageInfo

func (m *CreateBlogRequest) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type CreateBlogResponse struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBlogResponse) Reset()         { *m = CreateBlogResponse{} }
func (m *CreateBlogResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBlogResponse) ProtoMessage()    {}
func (*CreateBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_4f48964a2499a65d, []int{2}
}
func (m *CreateBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogResponse.Unmarshal(m, b)
}
func (m *CreateBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogResponse.Marshal(b, m, deterministic)
}
func (dst *CreateBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogResponse.Merge(dst, src)
}
func (m *CreateBlogResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBlogResponse.Size(m)
}
func (m *CreateBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogResponse proto.InternalMessageInfo

func (m *CreateBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type ReadBlogRequest struct {
	BlogId               string   `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBlogRequest) Reset()         { *m = ReadBlogRequest{} }
func (m *ReadBlogRequest) String() string { return proto.CompactTextString(m) }
func (*ReadBlogRequest) ProtoMessage()    {}
func (*ReadBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_4f48964a2499a65d, []int{3}
}
func (m *ReadBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlogRequest.Unmarshal(m, b)
}
func (m *ReadBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlogRequest.Marshal(b, m, deterministic)
}
func (dst *ReadBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlogRequest.Merge(dst, src)
}
func (m *ReadBlogRequest) XXX_Size() int {
	return xxx_messageInfo_ReadBlogRequest.Size(m)
}
func (m *ReadBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlogRequest proto.InternalMessageInfo

func (m *ReadBlogRequest) GetBlogId() string {
	if m != nil {
		return m.BlogId
	}
	return ""
}

type ReadBlogResponse struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBlogResponse) Reset()         { *m = ReadBlogResponse{} }
func (m *ReadBlogResponse) String() string { return proto.CompactTextString(m) }
func (*ReadBlogResponse) ProtoMessage()    {}
func (*ReadBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_4f48964a2499a65d, []int{4}
}
func (m *ReadBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlogResponse.Unmarshal(m, b)
}
func (m *ReadBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlogResponse.Marshal(b, m, deterministic)
}
func (dst *ReadBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlogResponse.Merge(dst, src)
}
func (m *ReadBlogResponse) XXX_Size() int {
	return xxx_messageInfo_ReadBlogResponse.Size(m)
}
func (m *ReadBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlogResponse proto.InternalMessageInfo

func (m *ReadBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type CreateNotifCodeRequest struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNotifCodeRequest) Reset()         { *m = CreateNotifCodeRequest{} }
func (m *CreateNotifCodeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNotifCodeRequest) ProtoMessage()    {}
func (*CreateNotifCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_4f48964a2499a65d, []int{5}
}
func (m *CreateNotifCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotifCodeRequest.Unmarshal(m, b)
}
func (m *CreateNotifCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotifCodeRequest.Marshal(b, m, deterministic)
}
func (dst *CreateNotifCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotifCodeRequest.Merge(dst, src)
}
func (m *CreateNotifCodeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNotifCodeRequest.Size(m)
}
func (m *CreateNotifCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotifCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotifCodeRequest proto.InternalMessageInfo

func (m *CreateNotifCodeRequest) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type UpdateBlogRequest struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBlogRequest) Reset()         { *m = UpdateBlogRequest{} }
func (m *UpdateBlogRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBlogRequest) ProtoMessage()    {}
func (*UpdateBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_4f48964a2499a65d, []int{6}
}
func (m *UpdateBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBlogRequest.Unmarshal(m, b)
}
func (m *UpdateBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBlogRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBlogRequest.Merge(dst, src)
}
func (m *UpdateBlogRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBlogRequest.Size(m)
}
func (m *UpdateBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBlogRequest proto.InternalMessageInfo

func (m *UpdateBlogRequest) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type UpdateBlogResponse struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBlogResponse) Reset()         { *m = UpdateBlogResponse{} }
func (m *UpdateBlogResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBlogResponse) ProtoMessage()    {}
func (*UpdateBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_4f48964a2499a65d, []int{7}
}
func (m *UpdateBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBlogResponse.Unmarshal(m, b)
}
func (m *UpdateBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBlogResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBlogResponse.Merge(dst, src)
}
func (m *UpdateBlogResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBlogResponse.Size(m)
}
func (m *UpdateBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBlogResponse proto.InternalMessageInfo

func (m *UpdateBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type CreateNotifCodeResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNotifCodeResponse) Reset()         { *m = CreateNotifCodeResponse{} }
func (m *CreateNotifCodeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNotifCodeResponse) ProtoMessage()    {}
func (*CreateNotifCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_4f48964a2499a65d, []int{8}
}
func (m *CreateNotifCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotifCodeResponse.Unmarshal(m, b)
}
func (m *CreateNotifCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotifCodeResponse.Marshal(b, m, deterministic)
}
func (dst *CreateNotifCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotifCodeResponse.Merge(dst, src)
}
func (m *CreateNotifCodeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNotifCodeResponse.Size(m)
}
func (m *CreateNotifCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotifCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotifCodeResponse proto.InternalMessageInfo

func (m *CreateNotifCodeResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type ListBlogRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBlogRequest) Reset()         { *m = ListBlogRequest{} }
func (m *ListBlogRequest) String() string { return proto.CompactTextString(m) }
func (*ListBlogRequest) ProtoMessage()    {}
func (*ListBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_4f48964a2499a65d, []int{9}
}
func (m *ListBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlogRequest.Unmarshal(m, b)
}
func (m *ListBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlogRequest.Marshal(b, m, deterministic)
}
func (dst *ListBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlogRequest.Merge(dst, src)
}
func (m *ListBlogRequest) XXX_Size() int {
	return xxx_messageInfo_ListBlogRequest.Size(m)
}
func (m *ListBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlogRequest proto.InternalMessageInfo

type ListBlogResponse struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBlogResponse) Reset()         { *m = ListBlogResponse{} }
func (m *ListBlogResponse) String() string { return proto.CompactTextString(m) }
func (*ListBlogResponse) ProtoMessage()    {}
func (*ListBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_blog_4f48964a2499a65d, []int{10}
}
func (m *ListBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlogResponse.Unmarshal(m, b)
}
func (m *ListBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlogResponse.Marshal(b, m, deterministic)
}
func (dst *ListBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlogResponse.Merge(dst, src)
}
func (m *ListBlogResponse) XXX_Size() int {
	return xxx_messageInfo_ListBlogResponse.Size(m)
}
func (m *ListBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlogResponse proto.InternalMessageInfo

func (m *ListBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

func init() {
	proto.RegisterType((*Blog)(nil), "blog.Blog")
	proto.RegisterType((*CreateBlogRequest)(nil), "blog.CreateBlogRequest")
	proto.RegisterType((*CreateBlogResponse)(nil), "blog.CreateBlogResponse")
	proto.RegisterType((*ReadBlogRequest)(nil), "blog.ReadBlogRequest")
	proto.RegisterType((*ReadBlogResponse)(nil), "blog.ReadBlogResponse")
	proto.RegisterType((*CreateNotifCodeRequest)(nil), "blog.CreateNotifCodeRequest")
	proto.RegisterType((*UpdateBlogRequest)(nil), "blog.UpdateBlogRequest")
	proto.RegisterType((*UpdateBlogResponse)(nil), "blog.UpdateBlogResponse")
	proto.RegisterType((*CreateNotifCodeResponse)(nil), "blog.CreateNotifCodeResponse")
	proto.RegisterType((*ListBlogRequest)(nil), "blog.ListBlogRequest")
	proto.RegisterType((*ListBlogResponse)(nil), "blog.ListBlogResponse")
	proto.RegisterEnum("blog.Blog_Gender", Blog_Gender_name, Blog_Gender_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlogServiceClient is the client API for BlogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogServiceClient interface {
	CreateBlog(ctx context.Context, in *CreateBlogRequest, opts ...grpc.CallOption) (*CreateBlogResponse, error)
	ReadBlog(ctx context.Context, in *ReadBlogRequest, opts ...grpc.CallOption) (*ReadBlogResponse, error)
	UpdateBlog(ctx context.Context, in *UpdateBlogRequest, opts ...grpc.CallOption) (*UpdateBlogResponse, error)
	CreateNotifCode(ctx context.Context, in *CreateNotifCodeRequest, opts ...grpc.CallOption) (*CreateNotifCodeResponse, error)
	ListBlog(ctx context.Context, in *ListBlogRequest, opts ...grpc.CallOption) (BlogService_ListBlogClient, error)
}

type blogServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlogServiceClient(cc *grpc.ClientConn) BlogServiceClient {
	return &blogServiceClient{cc}
}

func (c *blogServiceClient) CreateBlog(ctx context.Context, in *CreateBlogRequest, opts ...grpc.CallOption) (*CreateBlogResponse, error) {
	out := new(CreateBlogResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/CreateBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) ReadBlog(ctx context.Context, in *ReadBlogRequest, opts ...grpc.CallOption) (*ReadBlogResponse, error) {
	out := new(ReadBlogResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/ReadBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) UpdateBlog(ctx context.Context, in *UpdateBlogRequest, opts ...grpc.CallOption) (*UpdateBlogResponse, error) {
	out := new(UpdateBlogResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/UpdateBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) CreateNotifCode(ctx context.Context, in *CreateNotifCodeRequest, opts ...grpc.CallOption) (*CreateNotifCodeResponse, error) {
	out := new(CreateNotifCodeResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/CreateNotifCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) ListBlog(ctx context.Context, in *ListBlogRequest, opts ...grpc.CallOption) (BlogService_ListBlogClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BlogService_serviceDesc.Streams[0], "/blog.BlogService/ListBlog", opts...)
	if err != nil {
		return nil, err
	}
	x := &blogServiceListBlogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlogService_ListBlogClient interface {
	Recv() (*ListBlogResponse, error)
	grpc.ClientStream
}

type blogServiceListBlogClient struct {
	grpc.ClientStream
}

func (x *blogServiceListBlogClient) Recv() (*ListBlogResponse, error) {
	m := new(ListBlogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlogServiceServer is the server API for BlogService service.
type BlogServiceServer interface {
	CreateBlog(context.Context, *CreateBlogRequest) (*CreateBlogResponse, error)
	ReadBlog(context.Context, *ReadBlogRequest) (*ReadBlogResponse, error)
	UpdateBlog(context.Context, *UpdateBlogRequest) (*UpdateBlogResponse, error)
	CreateNotifCode(context.Context, *CreateNotifCodeRequest) (*CreateNotifCodeResponse, error)
	ListBlog(*ListBlogRequest, BlogService_ListBlogServer) error
}

func RegisterBlogServiceServer(s *grpc.Server, srv BlogServiceServer) {
	s.RegisterService(&_BlogService_serviceDesc, srv)
}

func _BlogService_CreateBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).CreateBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/CreateBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).CreateBlog(ctx, req.(*CreateBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_ReadBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).ReadBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/ReadBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).ReadBlog(ctx, req.(*ReadBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_UpdateBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).UpdateBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/UpdateBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).UpdateBlog(ctx, req.(*UpdateBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_CreateNotifCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotifCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).CreateNotifCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/CreateNotifCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).CreateNotifCode(ctx, req.(*CreateNotifCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_ListBlog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListBlogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlogServiceServer).ListBlog(m, &blogServiceListBlogServer{stream})
}

type BlogService_ListBlogServer interface {
	Send(*ListBlogResponse) error
	grpc.ServerStream
}

type blogServiceListBlogServer struct {
	grpc.ServerStream
}

func (x *blogServiceListBlogServer) Send(m *ListBlogResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _BlogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog.BlogService",
	HandlerType: (*BlogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBlog",
			Handler:    _BlogService_CreateBlog_Handler,
		},
		{
			MethodName: "ReadBlog",
			Handler:    _BlogService_ReadBlog_Handler,
		},
		{
			MethodName: "UpdateBlog",
			Handler:    _BlogService_UpdateBlog_Handler,
		},
		{
			MethodName: "CreateNotifCode",
			Handler:    _BlogService_CreateNotifCode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListBlog",
			Handler:       _BlogService_ListBlog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blog/blogpb/blog.proto",
}

func init() { proto.RegisterFile("blog/blogpb/blog.proto", fileDescriptor_blog_4f48964a2499a65d) }

var fileDescriptor_blog_4f48964a2499a65d = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcf, 0x8f, 0x93, 0x40,
	0x14, 0x16, 0x16, 0x68, 0xf7, 0x35, 0x6e, 0x97, 0x89, 0xc2, 0xa4, 0x71, 0x0d, 0xe1, 0x54, 0x3d,
	0x54, 0xa5, 0x1e, 0x34, 0x1e, 0x36, 0xd9, 0x4d, 0x34, 0x9b, 0x68, 0x0f, 0x18, 0x2f, 0x5e, 0x1a,
	0x70, 0x9e, 0x48, 0x82, 0x1d, 0x84, 0xa9, 0x89, 0x7f, 0xa4, 0x67, 0xff, 0x1d, 0x33, 0x33, 0x20,
	0x04, 0x34, 0xb2, 0x17, 0x78, 0xbf, 0xbe, 0x79, 0xdf, 0xfb, 0xde, 0x64, 0xc0, 0x4b, 0x0b, 0x9e,
	0x3d, 0x91, 0x9f, 0x32, 0x55, 0xbf, 0x4d, 0x59, 0x71, 0xc1, 0x89, 0x25, 0xed, 0xf0, 0xa7, 0x01,
	0xd6, 0x55, 0xc1, 0x33, 0x72, 0x06, 0x66, 0xce, 0xa8, 0x11, 0x18, 0xeb, 0xd3, 0xd8, 0xcc, 0x19,
	0xf1, 0x61, 0x76, 0xac, 0xb1, 0xda, 0xe7, 0x8c, 0x9a, 0x81, 0xb1, 0xb6, 0x63, 0x47, 0xba, 0x37,
	0x8c, 0xdc, 0x03, 0x5b, 0xe4, 0xa2, 0x40, 0x7a, 0xa2, 0x6a, 0xb5, 0x43, 0x08, 0x58, 0x29, 0x67,
	0x3f, 0xa8, 0xa5, 0x82, 0xca, 0x96, 0x31, 0x91, 0x64, 0x35, 0xb5, 0x83, 0x13, 0x19, 0x93, 0xb6,
	0x44, 0x97, 0x5f, 0xf8, 0x01, 0xa9, 0xa3, 0xd1, 0xca, 0x21, 0x8f, 0xc0, 0xc9, 0xf0, 0xc0, 0xb0,
	0xa2, 0xb3, 0xc0, 0x58, 0x9f, 0x45, 0xee, 0x46, 0x11, 0x95, 0xc4, 0x36, 0x6f, 0x54, 0x22, 0x6e,
	0x0a, 0xc2, 0x0b, 0x70, 0x74, 0x84, 0xcc, 0xc1, 0x7a, 0x97, 0x14, 0x78, 0x7e, 0x87, 0x9c, 0x82,
	0xfd, 0xfa, 0xab, 0x34, 0x8d, 0x70, 0x0b, 0xee, 0x75, 0x85, 0x89, 0x40, 0x89, 0x8d, 0xf1, 0xdb,
	0x11, 0x6b, 0x41, 0x1e, 0x82, 0x1a, 0x56, 0x4d, 0xb7, 0x88, 0xa0, 0x3b, 0x3c, 0xd6, 0x22, 0x3c,
	0x07, 0xd2, 0x07, 0xd5, 0x25, 0x3f, 0xd4, 0xf8, 0x5f, 0xd4, 0x63, 0x58, 0xc6, 0x98, 0xb0, 0x7e,
	0x23, 0x1f, 0x66, 0x32, 0xb5, 0xff, 0xa3, 0xa4, 0x23, 0xdd, 0x1b, 0x16, 0x46, 0x70, 0xde, 0xd5,
	0x4e, 0x3c, 0xff, 0x05, 0x78, 0x9a, 0xd5, 0x8e, 0x8b, 0xfc, 0xf3, 0x35, 0x67, 0x38, 0x75, 0x9e,
	0x2d, 0xb8, 0x1f, 0x4a, 0x76, 0x7b, 0x11, 0xfa, 0xa0, 0x89, 0x24, 0x9f, 0x81, 0x3f, 0x22, 0xd9,
	0x40, 0x3d, 0x70, 0x2a, 0xac, 0x8f, 0x85, 0x68, 0xb5, 0xd0, 0x5e, 0xe8, 0xc2, 0xf2, 0x6d, 0x5e,
	0x8b, 0x1e, 0x37, 0x29, 0x4f, 0x17, 0x9a, 0xd6, 0x39, 0xfa, 0x65, 0xc2, 0x42, 0xba, 0xef, 0xb1,
	0xfa, 0x9e, 0x7f, 0x42, 0x72, 0x09, 0xd0, 0x2d, 0x91, 0xf8, 0xba, 0x7e, 0x74, 0x17, 0x56, 0x74,
	0x9c, 0x68, 0x1a, 0xbe, 0x84, 0x79, 0xbb, 0x23, 0x72, 0x5f, 0x57, 0x0d, 0xf6, 0xbb, 0xf2, 0x86,
	0xe1, 0x06, 0x7a, 0x09, 0xd0, 0x69, 0xd7, 0xf6, 0x1e, 0xad, 0xa0, 0xed, 0xfd, 0x17, 0x99, 0x77,
	0xb0, 0x1c, 0xc8, 0x48, 0x1e, 0xf4, 0x89, 0x0e, 0xaf, 0xc0, 0xea, 0xe2, 0x1f, 0xd9, 0xe6, 0xbc,
	0x57, 0x30, 0x6f, 0x05, 0x6d, 0x67, 0x19, 0x68, 0xde, 0xce, 0x32, 0xd4, 0xfd, 0xa9, 0x71, 0x75,
	0xf7, 0xe3, 0xa2, 0xf7, 0x66, 0xa4, 0x8e, 0x7a, 0x2f, 0xb6, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x1a, 0x6f, 0x7d, 0x8a, 0x49, 0x04, 0x00, 0x00,
}
