// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webspice/notificationpb/notification.proto

package notificationpb // import "webspice/notificationpb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Notification_Status int32

const (
	Notification_DEACTIVE Notification_Status = 0
	Notification_ACTIVE   Notification_Status = 1
)

var Notification_Status_name = map[int32]string{
	0: "DEACTIVE",
	1: "ACTIVE",
}
var Notification_Status_value = map[string]int32{
	"DEACTIVE": 0,
	"ACTIVE":   1,
}

func (x Notification_Status) String() string {
	return proto.EnumName(Notification_Status_name, int32(x))
}
func (Notification_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_notification_b238d6111f83077e, []int{0, 0}
}

type Notification struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string              `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Code                 string              `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CreatedAt            string              `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeprecatedAt         string              `protobuf:"bytes,6,opt,name=deprecated_at,json=deprecatedAt,proto3" json:"deprecated_at,omitempty"`
	For                  string              `protobuf:"bytes,7,opt,name=for,proto3" json:"for,omitempty"`
	Status               Notification_Status `protobuf:"varint,8,opt,name=status,proto3,enum=webspice.Notification_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_notification_b238d6111f83077e, []int{0}
}
func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (dst *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(dst, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Notification) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Notification) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Notification) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Notification) GetDeprecatedAt() string {
	if m != nil {
		return m.DeprecatedAt
	}
	return ""
}

func (m *Notification) GetFor() string {
	if m != nil {
		return m.For
	}
	return ""
}

func (m *Notification) GetStatus() Notification_Status {
	if m != nil {
		return m.Status
	}
	return Notification_DEACTIVE
}

type CreateNotificationRequest struct {
	Notification         *Notification `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateNotificationRequest) Reset()         { *m = CreateNotificationRequest{} }
func (m *CreateNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNotificationRequest) ProtoMessage()    {}
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_notification_b238d6111f83077e, []int{1}
}
func (m *CreateNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotificationRequest.Unmarshal(m, b)
}
func (m *CreateNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotificationRequest.Marshal(b, m, deterministic)
}
func (dst *CreateNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotificationRequest.Merge(dst, src)
}
func (m *CreateNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNotificationRequest.Size(m)
}
func (m *CreateNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotificationRequest proto.InternalMessageInfo

func (m *CreateNotificationRequest) GetNotification() *Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

type CreateNotificationResponse struct {
	Notification         *Notification `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateNotificationResponse) Reset()         { *m = CreateNotificationResponse{} }
func (m *CreateNotificationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNotificationResponse) ProtoMessage()    {}
func (*CreateNotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_notification_b238d6111f83077e, []int{2}
}
func (m *CreateNotificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotificationResponse.Unmarshal(m, b)
}
func (m *CreateNotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotificationResponse.Marshal(b, m, deterministic)
}
func (dst *CreateNotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotificationResponse.Merge(dst, src)
}
func (m *CreateNotificationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNotificationResponse.Size(m)
}
func (m *CreateNotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotificationResponse proto.InternalMessageInfo

func (m *CreateNotificationResponse) GetNotification() *Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

type UpdateNotificationRequest struct {
	Notification         *Notification `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateNotificationRequest) Reset()         { *m = UpdateNotificationRequest{} }
func (m *UpdateNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNotificationRequest) ProtoMessage()    {}
func (*UpdateNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_notification_b238d6111f83077e, []int{3}
}
func (m *UpdateNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNotificationRequest.Unmarshal(m, b)
}
func (m *UpdateNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNotificationRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNotificationRequest.Merge(dst, src)
}
func (m *UpdateNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNotificationRequest.Size(m)
}
func (m *UpdateNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNotificationRequest proto.InternalMessageInfo

func (m *UpdateNotificationRequest) GetNotification() *Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

type UpdateNotificationResponse struct {
	Notification         *Notification `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateNotificationResponse) Reset()         { *m = UpdateNotificationResponse{} }
func (m *UpdateNotificationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateNotificationResponse) ProtoMessage()    {}
func (*UpdateNotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_notification_b238d6111f83077e, []int{4}
}
func (m *UpdateNotificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNotificationResponse.Unmarshal(m, b)
}
func (m *UpdateNotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNotificationResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateNotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNotificationResponse.Merge(dst, src)
}
func (m *UpdateNotificationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateNotificationResponse.Size(m)
}
func (m *UpdateNotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNotificationResponse proto.InternalMessageInfo

func (m *UpdateNotificationResponse) GetNotification() *Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

func init() {
	proto.RegisterType((*Notification)(nil), "webspice.Notification")
	proto.RegisterType((*CreateNotificationRequest)(nil), "webspice.CreateNotificationRequest")
	proto.RegisterType((*CreateNotificationResponse)(nil), "webspice.CreateNotificationResponse")
	proto.RegisterType((*UpdateNotificationRequest)(nil), "webspice.UpdateNotificationRequest")
	proto.RegisterType((*UpdateNotificationResponse)(nil), "webspice.UpdateNotificationResponse")
	proto.RegisterEnum("webspice.Notification_Status", Notification_Status_name, Notification_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WebspiceClient is the client API for Webspice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebspiceClient interface {
	// Notifications CU
	CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*CreateNotificationResponse, error)
	UpdateNotification(ctx context.Context, in *UpdateNotificationRequest, opts ...grpc.CallOption) (*UpdateNotificationResponse, error)
}

type webspiceClient struct {
	cc *grpc.ClientConn
}

func NewWebspiceClient(cc *grpc.ClientConn) WebspiceClient {
	return &webspiceClient{cc}
}

func (c *webspiceClient) CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*CreateNotificationResponse, error) {
	out := new(CreateNotificationResponse)
	err := c.cc.Invoke(ctx, "/webspice.Webspice/CreateNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webspiceClient) UpdateNotification(ctx context.Context, in *UpdateNotificationRequest, opts ...grpc.CallOption) (*UpdateNotificationResponse, error) {
	out := new(UpdateNotificationResponse)
	err := c.cc.Invoke(ctx, "/webspice.Webspice/UpdateNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebspiceServer is the server API for Webspice service.
type WebspiceServer interface {
	// Notifications CU
	CreateNotification(context.Context, *CreateNotificationRequest) (*CreateNotificationResponse, error)
	UpdateNotification(context.Context, *UpdateNotificationRequest) (*UpdateNotificationResponse, error)
}

func RegisterWebspiceServer(s *grpc.Server, srv WebspiceServer) {
	s.RegisterService(&_Webspice_serviceDesc, srv)
}

func _Webspice_CreateNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebspiceServer).CreateNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webspice.Webspice/CreateNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebspiceServer).CreateNotification(ctx, req.(*CreateNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webspice_UpdateNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebspiceServer).UpdateNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webspice.Webspice/UpdateNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebspiceServer).UpdateNotification(ctx, req.(*UpdateNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Webspice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webspice.Webspice",
	HandlerType: (*WebspiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNotification",
			Handler:    _Webspice_CreateNotification_Handler,
		},
		{
			MethodName: "UpdateNotification",
			Handler:    _Webspice_UpdateNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "webspice/notificationpb/notification.proto",
}

func init() {
	proto.RegisterFile("webspice/notificationpb/notification.proto", fileDescriptor_notification_b238d6111f83077e)
}

var fileDescriptor_notification_b238d6111f83077e = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xcf, 0x4f, 0xfa, 0x30,
	0x18, 0xc6, 0xbf, 0x85, 0x2f, 0x73, 0xbc, 0x4e, 0x42, 0xde, 0x18, 0x2d, 0x24, 0x24, 0x64, 0x78,
	0x20, 0x1e, 0x66, 0x82, 0xf1, 0xe2, 0x0d, 0x91, 0x83, 0x17, 0x0f, 0xf3, 0x07, 0xc6, 0x0b, 0x19,
	0x6b, 0x89, 0xbd, 0xac, 0x75, 0x2d, 0xf1, 0x9f, 0xf4, 0x1f, 0xf2, 0x66, 0x2c, 0x23, 0x94, 0xc0,
	0xbc, 0x10, 0x6f, 0x6f, 0x9f, 0x7e, 0xf2, 0xbc, 0xcf, 0x9e, 0xa5, 0x70, 0xfe, 0xc1, 0x67, 0x5a,
	0x89, 0x94, 0x5f, 0x64, 0xd2, 0x88, 0xb9, 0x48, 0x13, 0x23, 0x64, 0xa6, 0x66, 0x1b, 0xc7, 0x48,
	0xe5, 0xd2, 0x48, 0xf4, 0x57, 0x6c, 0xf8, 0x45, 0x20, 0xb8, 0x77, 0x00, 0x6c, 0x40, 0x45, 0x30,
	0x4a, 0xba, 0xa4, 0x5f, 0x8f, 0x2b, 0x82, 0xe1, 0x31, 0xd4, 0xd4, 0x9b, 0xcc, 0x38, 0xad, 0x58,
	0x69, 0x79, 0x40, 0x84, 0xff, 0xa9, 0x64, 0x9c, 0x56, 0xad, 0x68, 0x67, 0xec, 0x00, 0xa4, 0x39,
	0x4f, 0x0c, 0x67, 0xd3, 0xc4, 0xd0, 0x9a, 0xbd, 0xa9, 0x17, 0xca, 0xd0, 0x60, 0x0f, 0x8e, 0x18,
	0x57, 0x39, 0x4f, 0x57, 0x84, 0x67, 0x89, 0x60, 0x2d, 0x0e, 0x0d, 0x36, 0xa1, 0x3a, 0x97, 0x39,
	0x3d, 0xb0, 0x57, 0x3f, 0x23, 0x5e, 0x81, 0xa7, 0x4d, 0x62, 0x16, 0x9a, 0xfa, 0x5d, 0xd2, 0x6f,
	0x0c, 0x3a, 0xd1, 0x2a, 0x7b, 0xe4, 0xe6, 0x8e, 0x1e, 0x2c, 0x14, 0x17, 0x70, 0x18, 0x82, 0xb7,
	0x54, 0x30, 0x00, 0xff, 0x76, 0x3c, 0x1c, 0x3d, 0xde, 0x3d, 0x8f, 0x9b, 0xff, 0x10, 0xc0, 0x2b,
	0x66, 0x12, 0x4e, 0xa0, 0x35, 0xb2, 0xf1, 0x5c, 0xa3, 0x98, 0xbf, 0x2f, 0xb8, 0x36, 0x78, 0x0d,
	0x81, 0x5b, 0x9c, 0x6d, 0xe4, 0x70, 0x70, 0xb2, 0x7b, 0x7b, 0xbc, 0xc1, 0x86, 0x2f, 0xd0, 0xde,
	0x65, 0xac, 0x95, 0xcc, 0x34, 0xdf, 0xcb, 0x79, 0x02, 0xad, 0x27, 0xc5, 0xfe, 0x26, 0xf2, 0x2e,
	0xe3, 0xfd, 0x23, 0x0f, 0x3e, 0x09, 0xf8, 0x93, 0x82, 0xc3, 0x29, 0xe0, 0x76, 0x33, 0xd8, 0x5b,
	0x1b, 0x95, 0xfe, 0x90, 0xf6, 0xd9, 0xef, 0x50, 0x91, 0x74, 0x0a, 0xb8, 0xfd, 0x1d, 0xee, 0x82,
	0xd2, 0xfa, 0xdc, 0x05, 0xe5, 0x55, 0xdc, 0xb4, 0x5e, 0x4f, 0x4b, 0x1e, 0xda, 0xcc, 0xb3, 0x8f,
	0xeb, 0xf2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x89, 0x47, 0xb8, 0x93, 0x8a, 0x03, 0x00, 0x00,
}
